### ISSUE TITLE
Error on README + can't make it working

### ISSUE THREAD

**Issue by leotomas837** [jkroepke/helm-kubectl#3]
1) It looks like there is an error in the README.md. The template command is the following:

```
helm template <chart-name> --set-file=valuesKey=kubectl://<namespace>/<kind>/<name>/<output>
```

While then you give (several) examples as the below, with an extra `--set-file=hello`.

```
helm template <chart-name> --set-file=valuesKey=--set-file=hello=kubectl:///namespace/default
```

The second does not look correct. Could you clarify the syntax ?

2) I can't make it working. Could you clarify as well how to access the values in the `values.yaml` ? Kindly find below an example.

```
$> kubectl get node mynode -o jsonpath="{.metadata.labels.kubernetes\.io/os}{'\n'}"
linux
```

So the jsonpath works. My chart only includes a `Chart.yaml` and a `values.yaml` with the following content.

```
$> cat Chart.yaml
apiVersion: v2
name: temp
version: 1.0.0
$> cat values.yaml
mytestvalue: {{ .Files.Get "mytempfile" }}
```

And I get the following error (`.Files` is empty) by executing the following:

```
$> helm template . --set-file=mytempfile=kubectl:///node/mynode/jsonpath="{.metadata.labels.kubernetes\.io/os}{'\n'}"
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Files.Get \"mytempfile\"":interface {}(nil)}
```

Note that I tried simpler command, closer to the `README.md` as the below, but it does not work either:

```
helm template . --set-file='mytempfile=kubectl:///node/mynode/jsonpath={.metadata.labels.kubernetes\.io/os}'
```

Note that I also tried to access the supposed set file with other syntaxes in values.yaml, but none of them worked. So could you clarify how to use it to be able to 'lookup' current resources ?

**Comment by jkroepke** [comment]
it seems like on a shell, a lot of backslash are needed. This works for me:

```bash
% helm template values --set-file="mytempfile=kubectl:///nodes/aks-system01-82964380-vmss000000/jsonpath={.metadata.labels.kubernetes\\\\.io/os}"
---
# Source: values/templates/values.yaml
mytempfile: linux
```

**Comment by leotomas837** [comment]
Thanks for the quick answer ! Still does not work with the following command:

```
$> helm template . --set-file="mytempfile=kubectl:///nodes/mynode/jsonpath={.metadata.labels.kubernetes\\\\.io/os}"
Error: cannot load values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Files.Get \"mytempfile\"":interface {}(nil)}
```

Do your `Chart.yaml` and especially `values.yaml` have the exact content I put in my original message ?

Here are some details which can help:

```
$> helm version
version.BuildInfo{Version:"v3.10.1", GitCommit:"9f88ccb6aee40b9a0535fcc7efea6055e1ef72c9", GitTreeState:"clean", GoVersion:"go1.19.2"}
$> helm plugin list
NAME   	VERSION	DESCRIPTION
kubectl	1.0.0  	Helm plugin to support the helm lookup function in ArgoCD
...
```

My pc is Darwin arm64.

**Comment by leotomas837** [comment]
Also, why is your `values.yaml` in the `templates/` folder ? It is supposed to be in the root folder of the helm chart, in your case `values/`.

**Comment by jkroepke** [comment]
Here is the full command:

```
% helm template --version 1.0.3 --repo https://jkroepke.github.io/helm-charts/ values --set-file="mytempfile=kubectl:///nodes/aks-system01-82964380-vmss000000/jsonpath={.metadata.labels.kubernetes\\\\.io/os}"
---
# Source: values/templates/values.yaml
mytempfile: linux
```

And here is the chart: https://github.com/jkroepke/helm-charts/tree/main/charts/values

**Comment by jkroepke** [comment]
With version 1.0.1 of this plugin, the newline would also work in theory:

```
helm --debug template --version 1.0.3 --repo https://jkroepke.github.io/helm-charts/ values --set-file="mytempfile=kubectl:///nodes//jsonpath={.items[*].metadata.labels.kubernetes\\\\.io/os}{'\\\\n'}"
```

but the raw kubectl command will also not provide a newline:

```
% kubectl get nodes -o "jsonpath={.items[*].metadata.labels.kubernetes\.io/os}{'\n'}"
linux linux
```

**Comment by leotomas837** [comment]
So thanks to your example chart I made it working, I mean I have been able to inject some existing resource attributes into a template in the `templates/` folder. It also works with helmfile, by adding the additional `args` under `helmDefaults`, see below.

```
helmDefaults:
  args:
    - --set-file=mytempfile=kubectl:///nodes/mynode/jsonpath={.metadata.labels.kubernetes\\\\.io/os}
```

Yes I still have a question and a suggestion.

Question: Is this possible to inject values into `values.yaml` somehow ? Because when you have access to the templates, as your own dedicated chart under `templates`, the plugin with your example works fine. But the issue is when you want to install an external chart (under `dependencies[]` into `Chart.yaml`) and you want to inject some custom values into `values.yaml` with existing resource attributes. Is this completely out of scope ? Same issue with helmfile...

Suggestion: The plugin works, but for those who are interested, if the plugin currently only injects values into templates, then there is the [patch-operator](https://github.com/redhat-cop/patch-operator). It supports creation-time injection (multiple ones), as well as runtime patch enforcement (to resources not managed by argocd itself).

**Comment by leotomas837** [comment]
After checking, I am able to insert values into external charts. So It works too, it is the same as using 'lookup' in values.yaml. 

A last point yet: for those external charts, the `values.yaml` is fixed in the remote repo to properly feed the templates, for example for patch-operator it is [here](https://github.com/redhat-cop/patch-operator/blob/main/config/helmchart/values.yaml.tpl). The plugin works fine for injecting `replicaCount` for example, with the following command (the dummy `jsonpath={'2'}` is just for checking that the injection works ).

```
helm template --repo https://redhat-cop.github.io/patch-operator patch-operator --set-file="replicaCount=kubectl:///nodes/mynode/jsonpath={'2'}"
```

Yet what about more complex values, as the following (see the patch-operator `values.yaml`):

```
resources:
  requests:
    cpu: 100m
    memory: 250Mi
```

How can I replace them ? Is the plugin able to inject the `cpu` there ? I tried several options, one of them is replacing the `mytempfile` with something more complex with some `\n`, but can't make it working.

If that is implemented it would be major. By looking on the internet, I saw that lots of people have been looking to 'lookup' into `values.yaml` and several issues are open for helm, helmfile, argocd, etc about it.

**Comment by leotomas837** [comment]
My bad, everything works fine, with the following command for example, I am able to inject the cpu to `203m`:

```
helm template --repo https://redhat-cop.github.io/patch-operator patch-operator --set-file="resources.requests.cpu=kubectl:///nodes/mynode/jsonpath={'203m'}"
```

Thank you very much for the plugin mate, that is so useful ! I keep all my comments is case somebody wants to know how it works, they will understand by reading.
